# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-project5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-project5
  template:
    metadata:
      labels:
        app: udacity-project5
    spec:
      containers:
        - name: udacity-project5
          image: nganpv/udacity-devops-project5:latest
          ports:
            - containerPort: 8080
